# Finite differences

In [16]:
import numpy as np
from scipy.sparse import lil_matrix

In [94]:
n=5

In [96]:
mat = lil_matrix((n,n))
for i in range(n):
    if i == 0:
        mat[i,i] =1
    elif i == n-1:
        mat[i,i] = 1
    else:
        mat[i,i] = -2
        mat[i,i-1] = 1
        mat[i,i+1] = 1
        
mat = mat.toarray()
print(mat)


[[ 1.  0.  0.  0.  0.]
 [ 1. -2.  1.  0.  0.]
 [ 0.  1. -2.  1.  0.]
 [ 0.  0.  1. -2.  1.]
 [ 0.  0.  0.  0.  1.]]
