In [1]:
import pandas as pd
import numpy as np

<jemalloc>: Unsupported system page size


In [2]:
data = pd.read_csv("3_body_input_and_tests_0.txt",sep='\s+')

In [3]:
row = data.iloc[2]
piece_of_data = row.loc["m1"]


In [7]:
c = np.array([1,3,5,-7,4,2,4,6])
np.abs(c+2)

array([3, 5, 7, 5, 6, 4, 6, 8])

In [4]:
print(f"row {row}")

row name        Test3
pos1x         1.0
pos1y         1.0
pos2x        -1.0
pos2y        -1.0
pos3x         0.0
pos3y         0.0
vel1x         0.0
vel1y         0.0
vel2x         0.0
vel2y         0.0
vel3x         0.0
vel3y         0.0
m1           1000
m2           1000
m3              0
tstep      0.0001
epsilon         0
period        1.0
energy        0.0
angmom          0
Name: 2, dtype: object


In [5]:
print(f"piece_of_data {piece_of_data}")

piece_of_data 1000


In [17]:
b=(data.iloc[12]).loc["m3"]
print(b)

1


In [18]:
y= np.zeros((3,6))
y[2,4] = b
print(y)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


In [8]:
a=np.array([[1,2],[3,4],[5,6]])

In [9]:
a[0,0] = 7

In [10]:
a

array([[7, 2],
       [3, 4],
       [5, 6]])