In [1]:
import pandas as pd
import numpy as np
import os

<jemalloc>: Unsupported system page size


In [34]:
data = pd.read_csv("3_body_input_and_tests_0.txt",sep='\s+')
names = data.iloc[:,0]

In [44]:
def Keplers_third(da, na):
    """A function which will plot the semi-major axis and period of orbiting bodies.
    In:
        da: Initial condition data
        na: names of the systems"""



    for K in range(len(na)):
        file = f"n_body_data/produced_data_system_{na[K]}.txt"
        if os.path.exists(file) == False:
            continue
        else:
            orbit_data=pd.read_csv(file, sep="\s+")
            in_con = da.iloc[r]
            ma = np.array([in_con.loc["m1"], in_con.loc["m2"], in_con.loc["m3"]])
            system_time = orbit_data["time"]
            for i in range(len(masses)):
                if ma[i] == 0:
                    ma = np.delete(masses, i)

   

In [45]:
Keplers_third(data,names)

NameError: name 'r' is not defined

In [3]:
name = "BrouA7"
produced_data_name = f"n_body_data/produced_data_system_{name}.txt"
produced_data = pd.read_csv(produced_data_name,sep="\s+")
no_masses = int((produced_data.shape[1] -3)/4)
print(produced_data.shape[1])

print(no_masses)

17
3


In [33]:
# import numpy package
import numpy as np

# create an numpy array 
a = np.array([1, 2, 3, 4, 8, 6, 7, 3, 9, 10])

# display index value of 3
print("All index value of 3 is: ", np.where(a == 3))

print("First index value of 3 is: ",np.where(a==3)[0][0])

All index value of 3 is:  (array([2, 7]),)
First index value of 3 is:  2


In [4]:
m = np.array([1,2,3])
n = np.array([[1,2],[3,4],[5,6]])
result = n * m[:, np.newaxis]  # reshape m to (3,1)
print(result)

[[ 1  2]
 [ 6  8]
 [15 18]]


In [5]:
p = np.array([1,2])
q = np.array([[1,2],[3,4]])
result = q * p[:, np.newaxis]  # reshape m to (3,1)
print(result)

[[1 2]
 [6 8]]


In [6]:
result = n * m[:, np.newaxis]  # reshape m to (3,1)
print(result)

[[ 1  2]
 [ 6  8]
 [15 18]]


In [10]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([8,9,1,4,4,2,4,3,5])
np.linalg.norm((a,b),axis=0)

array([ 8.06225775,  9.21954446,  3.16227766,  5.65685425,  6.40312424,
        6.32455532,  8.06225775,  8.54400375, 10.29563014])

In [17]:
c = np.array([-2,5,1,-7,3,6,2,-6,-7,8,-11,2])
d = 5
np.argmin(np.abs(c-d))

np.int64(1)

In [31]:
e= np.array([-2,-1,0,1,2])
f= np.array([-2,-1,0,1,2])
np.linalg.norm((e,f),axis=0)

array([2.82842712, 1.41421356, 0.        , 1.41421356, 2.82842712])

In [15]:
5%3

2

In [13]:
na = data.iloc[:,0]
for K in range(len(na)):
    if os.path.exists(f"n_body_data/produced_data_system_{na[K]}.txt") == False:
        print(f"n_body_data/produced_data_system_{na[K]}")
        print("no")
    else:
        print("yes")

yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
n_body_data/produced_data_system_Bfly1
no
yes
yes
yes
yes
yes
yes
yes
yes


In [13]:
row = data.iloc[2]
piece_of_data = row.loc["m1"]


In [15]:
c = np.array([1,3,5,-7,4,2,4,6])
np.abs(c+2)

array([3, 5, 7, 5, 6, 4, 6, 8])

In [19]:
np.linalg.norm((2,3))

3.605551275463989

In [27]:
a = 5.34546
np.round(a,-2)

0.0

In [17]:
for i in range(5):
    print(i)
    if i ==3:
        continue
        print("break")
        
    else:
        print("not break")

print(i)

0
not break
1
not break
2
not break
3
4
not break
4


In [5]:
for i in range(5):
    print(i)
    if i ==3:
        print("break")
        break
    else:
        print("not break")

print(i)

0
not break
1
not break
2
not break
3
break
3


In [4]:
print(f"row {row}")

row name        Test3
pos1x         1.0
pos1y         1.0
pos2x        -1.0
pos2y        -1.0
pos3x         0.0
pos3y         0.0
vel1x         0.0
vel1y         0.0
vel2x         0.0
vel2y         0.0
vel3x         0.0
vel3y         0.0
m1           1000
m2           1000
m3              0
tstep      0.0001
epsilon         0
period        1.0
energy        0.0
angmom          0
Name: 2, dtype: object


In [5]:
print(f"piece_of_data {piece_of_data}")

piece_of_data 1000


In [17]:
b=(data.iloc[12]).loc["m3"]
print(b)

1


In [18]:
y= np.zeros((3,6))
y[2,4] = b
print(y)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


In [8]:
a=np.array([[1,2],[3,4],[5,6]])

In [9]:
a[0,0] = 7

In [10]:
a

array([[7, 2],
       [3, 4],
       [5, 6]])